language: ruby
cache: bundler

rvm:
  - 2.5.8
  - 2.7.2

services:
  - postgresql

gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.1.gemfile

deploy:
  provider: rubygems
  api_key:
    secure: "C9iAATKay2RKJ191DOTXHFgEkWQT6nzHpvlJF8VkbmY7gAj8fyYX4pEEX4c7WL1K1MADlJVEUpgESUL9NsvaJply36HbHkK7Q4OjcMo6KMLvzQsniW9We6tI3mEjjWxomUTKLF/YZGhk8TduvbYdCjInAi+eHx3rF8f3hVm7BNc="
  on:
    tags: true
