language: ruby
cache: bundler
sudo: false

rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8

gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
