language: ruby
cache: bundler

rvm:
  - 2.5.8
  - 2.7.2
env:
  matrix:
    - PG_VERSION=11

before_install:
  - git config --global user.name "Prodder In Travis-CI"
  - git config --global user.email "prodder@example.com"
  # install postgres
  - sudo apt-get install postgresql-client-$PG_VERSION postgresql-server-dev-$PG_VERSION
  # setup pg_dump
  - ls -al /usr/lib/postgresql/
  - sudo ln -sfn /usr/lib/postgresql/$PG_VERSION/bin/pg_dump /usr/bin/pg_dump
  # start up the specific version of PG
  - sudo -E sh -c 'service postgresql stop'
  - sleep 5s
  - sudo -E sh -c 'service postgresql start $PG_VERSION'
  - psql -U postgres -d postgres -c 'select setting from pg_settings where name = $m$server_version$m$;'

gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.1.gemfile

deploy:
  provider: rubygems
  api_key:
    secure: "C9iAATKay2RKJ191DOTXHFgEkWQT6nzHpvlJF8VkbmY7gAj8fyYX4pEEX4c7WL1K1MADlJVEUpgESUL9NsvaJply36HbHkK7Q4OjcMo6KMLvzQsniW9We6tI3mEjjWxomUTKLF/YZGhk8TduvbYdCjInAi+eHx3rF8f3hVm7BNc="
  on:
    tags: true
